/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package theclinic.view.views.non_modal_views;

import theclinic.controller.ViewController;
import theclinic.view.View;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author colin
 */
public class PatientRecallerView extends View
                                 implements ActionListener{
    enum Actions{
        REQUEST_CLOSE_VIEW,
        REQUEST_RECALL_PREVIEW,
        REQUEST_RECALL_TYPE_GBT,
        REQUEST_RECALL_TYPE_NON_GBT,
        REQUEST_RECALL_STATUS_ACTIVE,
        REQUEST_RECALL_STATUS_INACTIVE,
        REQUEST_RECALL_STATUS_SUSPENDED, 
    }

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public PatientRecallerView(View.Viewer myViewType, 
            ViewController myController,
            DesktopView desktopView) {
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);
        
    }
    
    public void actionPerformed(ActionEvent e){
        Actions actionCommand = Actions.valueOf(e.getActionCommand());
        switch(actionCommand){
            case REQUEST_CLOSE_VIEW ->{
                
            }
            case REQUEST_RECALL_PREVIEW ->{
                
            }
            case REQUEST_RECALL_TYPE_GBT ->{
                
            }
            case REQUEST_RECALL_TYPE_NON_GBT ->{
                
            }
            case REQUEST_RECALL_STATUS_ACTIVE ->{
                
            }
            case REQUEST_RECALL_STATUS_INACTIVE ->{
                
            }
            case REQUEST_RECALL_STATUS_SUSPENDED ->{
                
            }
        }
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        this.bgRecallStatus.add(this.rdbActiveSelector);
        this.bgRecallStatus.add(this.rdbInactiveSelector);
        this.bgRecallStatus.add(this.rdbSuspendedSelector);
        this.bgRecallType.add(this.rdbNonGBTSelector);
        this.bgRecallType.add(this.rdbGBTSelector);
        rdbActiveSelector.setActionCommand(Actions.REQUEST_RECALL_STATUS_ACTIVE.toString());
        rdbInactiveSelector.setActionCommand(Actions.REQUEST_RECALL_STATUS_INACTIVE.toString());
        rdbSuspendedSelector.setActionCommand(Actions.REQUEST_RECALL_STATUS_SUSPENDED.toString());
        rdbNonGBTSelector.setActionCommand(Actions.REQUEST_RECALL_TYPE_NON_GBT.toString());
        rdbGBTSelector.setActionCommand(Actions.REQUEST_RECALL_TYPE_GBT.toString());
        this.btnCloseView.setActionCommand(Actions.REQUEST_CLOSE_VIEW.toString());
        this.btnPreviewSelectedRecalls.setActionCommand(Actions.REQUEST_RECALL_PREVIEW.toString());
        rdbActiveSelector.addActionListener(this);
        rdbInactiveSelector.addActionListener(this);
        rdbSuspendedSelector.addActionListener(this);
        rdbNonGBTSelector.addActionListener(this);
        rdbGBTSelector.addActionListener(this);
        this.btnCloseView.addActionListener(this);
        this.btnPreviewSelectedRecalls.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bgRecallType = new javax.swing.ButtonGroup();
        bgRecallStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rdbGBTSelector = new javax.swing.JRadioButton();
        rdbNonGBTSelector = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        rdbActiveSelector = new javax.swing.JRadioButton();
        rdbInactiveSelector = new javax.swing.JRadioButton();
        rdbSuspendedSelector = new javax.swing.JRadioButton();
        btnPreviewSelectedRecalls = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Patient recaller");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scheduled recalls"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Select recall type"));
        jPanel4.setPreferredSize(new java.awt.Dimension(138, 146));

        rdbGBTSelector.setText("GBT");

        rdbNonGBTSelector.setText("non-GBT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbGBTSelector)
                    .addComponent(rdbNonGBTSelector))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rdbGBTSelector)
                .addGap(18, 18, 18)
                .addComponent(rdbNonGBTSelector)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Select recall status"));

        rdbActiveSelector.setText("ACTIVE");

        rdbInactiveSelector.setText("INACTIVE");

        rdbSuspendedSelector.setText("SUSPENDED");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSuspendedSelector)
                    .addComponent(rdbActiveSelector)
                    .addComponent(rdbInactiveSelector))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rdbActiveSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbInactiveSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbSuspendedSelector)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnPreviewSelectedRecalls.setText("<html><center>Preview</center><center>selected</center><center>recall(s)</center></html>");

        btnCloseView.setText("<html><center>Close</center><center>view</center></html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPreviewSelectedRecalls)
                    .addComponent(btnCloseView)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPreviewSelectedRecalls, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloseView, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRecallStatus;
    private javax.swing.ButtonGroup bgRecallType;
    private javax.swing.JButton btnCloseView;
    private javax.swing.JButton btnPreviewSelectedRecalls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbActiveSelector;
    private javax.swing.JRadioButton rdbGBTSelector;
    private javax.swing.JRadioButton rdbInactiveSelector;
    private javax.swing.JRadioButton rdbNonGBTSelector;
    private javax.swing.JRadioButton rdbSuspendedSelector;
    // End of variables declaration//GEN-END:variables
}
