/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package theclinic.view.views.non_modal_views;

/**
 *
 * @author colin
 */
public class TestNotificationView extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TestNotificationView() {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlOperations = new javax.swing.JPanel();
        btnEditSelectedNotification = new javax.swing.JButton();
        btnDeleteSelectedNotification = new javax.swing.JButton();
        btnActionSelectedNotifications = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();
        btnAddNewNotification = new javax.swing.JButton();
        pnlRadioButtonsAndColourKey = new javax.swing.JPanel();
        pnlColourKey = new javax.swing.JPanel();
        lblBlack = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        lblGreen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlDisplayControls = new javax.swing.JPanel();
        rdbDisplayUnactionedNotifications = new javax.swing.JRadioButton();
        rdbDisplayAllNotifications = new javax.swing.JRadioButton();
        pnlNotificaionTable = new javax.swing.JPanel();
        scrPatientNotificationView = new javax.swing.JScrollPane();

        pnlOperations.setBorder(javax.swing.BorderFactory.createTitledBorder("Operations"));
        pnlOperations.setPreferredSize(new java.awt.Dimension(142, 500));

        btnEditSelectedNotification.setText("<html><center>Update</center><center>selected</center><center>notification</center></html>");

        btnDeleteSelectedNotification.setText("<html><center>Delete</center><center>selected</center><center>notification</center></html>");

        btnActionSelectedNotifications.setText("<html><center>Action</center><center>selected</center><center>notification(s)</center></html>");

        btnCloseView.setText("<html><center>Close</center><center>view</center></html>");

        btnAddNewNotification.setText("<html><center>Add</center><center>notification</center>");

        javax.swing.GroupLayout pnlOperationsLayout = new javax.swing.GroupLayout(pnlOperations);
        pnlOperations.setLayout(pnlOperationsLayout);
        pnlOperationsLayout.setHorizontalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActionSelectedNotifications)
                    .addComponent(btnCloseView)
                    .addComponent(btnEditSelectedNotification)
                    .addComponent(btnAddNewNotification)
                    .addComponent(btnDeleteSelectedNotification))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlOperationsLayout.setVerticalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNewNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditSelectedNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteSelectedNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActionSelectedNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnCloseView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlColourKey.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notification colour key", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblBlack.setBackground(new java.awt.Color(255, 255, 0));
        lblBlack.setForeground(java.awt.Color.red);
        lblBlack.setOpaque(true);

        lblBlue.setBackground(java.awt.Color.yellow);
        lblBlue.setText(" ");
        lblBlue.setOpaque(true);
        lblBlue.setBackground(java.awt.Color.BLUE);

        lblGreen.setBackground(java.awt.Color.yellow);
        lblGreen.setText(" ");
        lblGreen.setOpaque(true);
        lblGreen.setBackground(java.awt.Color.GREEN);

        jLabel1.setText("patient notifications not yet due");

        jLabel3.setText("overdue patient notifications");

        jLabel4.setText("patient notifications which have been actioned");

        javax.swing.GroupLayout pnlColourKeyLayout = new javax.swing.GroupLayout(pnlColourKey);
        pnlColourKey.setLayout(pnlColourKeyLayout);
        pnlColourKeyLayout.setHorizontalGroup(
            pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColourKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBlack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlue, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(lblGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlColourKeyLayout.setVerticalGroup(
            pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColourKeyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColourKeyLayout.createSequentialGroup()
                        .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlColourKeyLayout.createSequentialGroup()
                        .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(26, 26, 26))
        );

        buttonGroup1.add(rdbDisplayUnactionedNotifications);
        rdbDisplayUnactionedNotifications.setSelected(true);
        rdbDisplayUnactionedNotifications.setText(DISPLAY_UNACTIONED_NOTIFICATIONS_TEXT);

        buttonGroup1.add(rdbDisplayAllNotifications);
        rdbDisplayAllNotifications.setText(DISPLAY_ALL_NOTIFICATIONS_TEXT);

        javax.swing.GroupLayout pnlDisplayControlsLayout = new javax.swing.GroupLayout(pnlDisplayControls);
        pnlDisplayControls.setLayout(pnlDisplayControlsLayout);
        pnlDisplayControlsLayout.setHorizontalGroup(
            pnlDisplayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayControlsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlDisplayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbDisplayAllNotifications)
                    .addComponent(rdbDisplayUnactionedNotifications))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlDisplayControlsLayout.setVerticalGroup(
            pnlDisplayControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayControlsLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(rdbDisplayUnactionedNotifications)
                .addGap(18, 18, 18)
                .addComponent(rdbDisplayAllNotifications)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout pnlRadioButtonsAndColourKeyLayout = new javax.swing.GroupLayout(pnlRadioButtonsAndColourKey);
        pnlRadioButtonsAndColourKey.setLayout(pnlRadioButtonsAndColourKeyLayout);
        pnlRadioButtonsAndColourKeyLayout.setHorizontalGroup(
            pnlRadioButtonsAndColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioButtonsAndColourKeyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDisplayControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(pnlColourKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        pnlRadioButtonsAndColourKeyLayout.setVerticalGroup(
            pnlRadioButtonsAndColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioButtonsAndColourKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRadioButtonsAndColourKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColourKey, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(pnlDisplayControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        scrPatientNotificationView.setPreferredSize(new java.awt.Dimension(100, 750));

        javax.swing.GroupLayout pnlNotificaionTableLayout = new javax.swing.GroupLayout(pnlNotificaionTable);
        pnlNotificaionTable.setLayout(pnlNotificaionTableLayout);
        pnlNotificaionTableLayout.setHorizontalGroup(
            pnlNotificaionTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificaionTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPatientNotificationView, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNotificaionTableLayout.setVerticalGroup(
            pnlNotificaionTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotificaionTableLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scrPatientNotificationView, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNotificaionTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRadioButtonsAndColourKey, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNotificaionTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlRadioButtonsAndColourKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActionSelectedNotifications;
    private javax.swing.JButton btnAddNewNotification;
    private javax.swing.JButton btnCloseView;
    private javax.swing.JButton btnDeleteSelectedNotification;
    private javax.swing.JButton btnEditSelectedNotification;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBlack;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JPanel pnlColourKey;
    private javax.swing.JPanel pnlDisplayControls;
    private javax.swing.JPanel pnlNotificaionTable;
    private javax.swing.JPanel pnlOperations;
    private javax.swing.JPanel pnlRadioButtonsAndColourKey;
    private javax.swing.JRadioButton rdbDisplayAllNotifications;
    private javax.swing.JRadioButton rdbDisplayUnactionedNotifications;
    private javax.swing.JScrollPane scrPatientNotificationView;
    // End of variables declaration//GEN-END:variables

}
