/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package colinhewlettsolutions.client.view.views.non_modal_views;

import colinhewlettsolutions.client.controller.SystemDefinition.Properties;
import colinhewlettsolutions.client.controller.ViewController;
import colinhewlettsolutions.client.controller.LoginViewController;
import colinhewlettsolutions.client.model.non_entity.Credential;
import colinhewlettsolutions.client.view.View;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import javax.swing.border.TitledBorder;
import javax.swing.JOptionPane;


/**
 *
 * @author colin
 */
public class LoginOldPasswordCheckView extends View
                                           implements ActionListener, PropertyChangeListener{

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public LoginOldPasswordCheckView( 
            View.Viewer myViewType, 
            ViewController myController,
            DesktopView desktopView) {//ViewMode arg
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView); 
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        LoginViewController.Actions actionRequestToController = null;
        Action actionCommand = Action.valueOf(e.getActionCommand());
        switch (actionCommand){
            case REQUEST_CANCEL ->{
                try{//close view and controller
                    this.setClosed(true);
                }catch (PropertyVetoException ex){

                }
                ActionEvent actionEvent = new ActionEvent(
                        this,ActionEvent.ACTION_PERFORMED,
                        LoginViewController.Actions.VIEW_CLOSED_NOTIFICATION.toString());
                getMyController().actionPerformed(actionEvent);
                break;
            }
            case REQUEST_NEXT ->{
                Credential credential = new Credential();
                credential.setPassword(this.txtPassword.getPassword());
                getMyController().getDescriptor().getViewDescription().
                        setProperty(Properties.LOGIN_CREDENTIAL, credential);
                actionRequestToController = LoginViewController.Actions.OLD_PASSWORD_CHECK_REQUEST;
                doSendActionEvent(actionRequestToController);
                break;
            }
        }  
    }
    
    @Override 
    public void propertyChange(PropertyChangeEvent e) {
        String message = null;
        LoginViewController.Properties property = 
                LoginViewController.Properties.valueOf(e.getPropertyName());
        switch(property){
            case CORRECT_LOGIN_CREDENTIAL_RECEIVED ->{
                try{//nb -- controller would have change the LoginViewMode when handling VIEW_CLOSED_NOTIFICATION
                    this.setClosed(true);
                }catch (PropertyVetoException ex){

                }
                break;
            }
            case INCORRECT_PASSWORD_RECEIVED ->{
                message = "Incorrect password received for the current user";
                JOptionPane.showInternalMessageDialog(this, message, "View error", JOptionPane.WARNING_MESSAGE);
                break;
            }
        }
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        setVisible(true);
        TitledBorder border = (TitledBorder) pnlPassword.getBorder();
        Credential credential = (Credential)getMyController().getDescriptor().
                getControllerDescription().getProperty(Properties.LOGIN_CREDENTIAL);
        String username = credential.getUsername();
        username = username.substring(0,1).toUpperCase() + username.substring(1);
        border.setTitle("Enter password for '" + username + "'");  
        this.btnCancel.setActionCommand(Action.REQUEST_CANCEL.toString());
        this.btnCancel.addActionListener(this);
        this.btnNext.setActionCommand(Action.REQUEST_NEXT.toString());
        this.btnNext.addActionListener(this);
    }
    
    private void doSendActionEvent(
        LoginViewController.Actions actionCommand){
        ActionEvent actionEvent = new ActionEvent(
            this,ActionEvent.ACTION_PERFORMED,
            actionCommand.toString());
        getMyController().actionPerformed(actionEvent);
    }

    enum Action{
        REQUEST_CANCEL,
        REQUEST_NEXT
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        pnlAction = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("Password checker");

        pnlPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter password for <user>"));

        javax.swing.GroupLayout pnlPasswordLayout = new javax.swing.GroupLayout(pnlPassword);
        pnlPassword.setLayout(pnlPasswordLayout);
        pnlPasswordLayout.setHorizontalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPasswordLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlPasswordLayout.setVerticalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pnlAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnNext.setText("Enter");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout pnlActionLayout = new javax.swing.GroupLayout(pnlAction);
        pnlAction.setLayout(pnlActionLayout);
        pnlActionLayout.setHorizontalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        pnlActionLayout.setVerticalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel pnlAction;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
