/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package colinhewlettsolutions.client.view.views.modal_views;

import colinhewlettsolutions.client.controller.SystemDefinition;
import colinhewlettsolutions.client.controller.ViewController;
import colinhewlettsolutions.client.controller.PatientViewController;
import colinhewlettsolutions.client.model.entity.Patient;
import colinhewlettsolutions.client.view.View;
import colinhewlettsolutions.client.view.views.non_modal_views.DesktopView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author colin
 */
public class ModalPatientSelectorView extends ModalView
                                      implements ActionListener{
    
    enum Action{
        REQUEST_CLOSE_VIEW,
        REQUEST_PATIENT_RESTORE,
    }
    
    public ModalPatientSelectorView(
            View.Viewer myViewType,
            ViewController myController, 
            DesktopView desktopView){ 
        setTitle("Patient selector view");
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        Action actionCommand = Action.valueOf(e.getActionCommand());
        switch(actionCommand){
            case REQUEST_CLOSE_VIEW ->{
                try{
                    this.setClosed(true);
                }catch (PropertyVetoException ex){

                }
                break;
            }
            case REQUEST_PATIENT_RESTORE ->{
                if (cmbPatientSelector.getSelectedIndex()!=-1){                    
                    Patient patient = (Patient)cmbPatientSelector.getSelectedItem();
                    getMyController().getDescriptor().getViewDescription().setProperty(SystemDefinition.Properties.PATIENT, patient);
                    ActionEvent actionEvent = new ActionEvent(
                            this,ActionEvent.ACTION_PERFORMED, 
                            PatientViewController.Actions.PATIENT_RESTORE_REQUEST.toString());
                    this.getMyController().actionPerformed(actionEvent);
                    try{
                        this.setClosed(true);
                    }catch (PropertyVetoException ex){

                    }
                }else{
                    String message = "You have not selected a patient to restrore yet";
                    JOptionPane.showInternalMessageDialog(this, message,"View error",JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
        }
    }
    
    @Override
    public void initialiseView(){
        initComponents(); 
        this.btnCloseView.setActionCommand(Action.REQUEST_CLOSE_VIEW.toString());
        this.btnCloseView.addActionListener(this);
        this.btnRestoreSelectedPatient.setActionCommand(Action.REQUEST_PATIENT_RESTORE.toString());
        this.btnRestoreSelectedPatient.addActionListener(this);
        populatePatientSelector();
        this.setVisible(true);
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent e){
        if (e.getPropertyName().equals(
            ViewController.PatientViewControllerPropertyChangeEvent.PATIENTS_RECEIVED.toString())){
            this.populatePatientSelector();
        }
    }
    
    private void populatePatientSelector(){
        DefaultComboBoxModel<Patient> model = 
                new DefaultComboBoxModel<>();
        ArrayList<Patient> patients = 
                (ArrayList<Patient>)getMyController().getDescriptor().
                        getControllerDescription().getProperty(SystemDefinition.Properties.PATIENTS);
        Iterator<Patient> it = patients.iterator();
        while (it.hasNext()){
            Patient patient = it.next();
            model.addElement(patient);
        }
        this.cmbPatientSelector.setModel(model);
        Patient patient = (Patient)getMyController().getDescriptor().
                getControllerDescription().getProperty(SystemDefinition.Properties.PATIENT);
        if (patient!=null){
            if (patient.getIsKeyDefined())
                this.cmbPatientSelector.setSelectedItem(patient);
            else this.cmbPatientSelector.setSelectedIndex(-1);
        }
        else this.cmbPatientSelector.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPatientSelector = new javax.swing.JPanel();
        cmbPatientSelector = new javax.swing.JComboBox<>();
        pnlAction = new javax.swing.JPanel();
        btnRestoreSelectedPatient = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();

        pnlPatientSelector.setBorder(javax.swing.BorderFactory.createTitledBorder("Select patient to restore"));

        cmbPatientSelector.setModel(new javax.swing.DefaultComboBoxModel<>());

        javax.swing.GroupLayout pnlPatientSelectorLayout = new javax.swing.GroupLayout(pnlPatientSelector);
        pnlPatientSelector.setLayout(pnlPatientSelectorLayout);
        pnlPatientSelectorLayout.setHorizontalGroup(
            pnlPatientSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientSelectorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmbPatientSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlPatientSelectorLayout.setVerticalGroup(
            pnlPatientSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientSelectorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cmbPatientSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnRestoreSelectedPatient.setText("<html><center>Restore selected</center><center>patient</center></html><html><center>Restore</center><center>selected</center><center>patient</center></html>");

        btnCloseView.setText("<html><center>Close</center><center>view</center></html>");

        javax.swing.GroupLayout pnlActionLayout = new javax.swing.GroupLayout(pnlAction);
        pnlAction.setLayout(pnlActionLayout);
        pnlActionLayout.setHorizontalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestoreSelectedPatient)
                    .addComponent(btnCloseView))
                .addGap(12, 12, 12))
        );
        pnlActionLayout.setVerticalGroup(
            pnlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionLayout.createSequentialGroup()
                .addComponent(btnRestoreSelectedPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCloseView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlPatientSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPatientSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseView;
    private javax.swing.JButton btnRestoreSelectedPatient;
    private javax.swing.JComboBox<Patient> cmbPatientSelector;
    private javax.swing.JPanel pnlAction;
    private javax.swing.JPanel pnlPatientSelector;
    // End of variables declaration//GEN-END:variables
}
