/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package colinhewlettsolutions.client.view.views.modal_views;

import colinhewlettsolutions.client.controller.ScheduleViewController;
import colinhewlettsolutions.client.controller.ViewController;
import colinhewlettsolutions.client.view.View;
import colinhewlettsolutions.client.view.views.non_modal_views.DesktopView;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JCheckBox;
import javax.swing.DefaultListModel;

/**
 *
 * @author colin
 */
public class ModalCheckBoxListView extends ModalView {

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalCheckBoxListView(
            View.Viewer myViewType,
            ViewController myController, 
            DesktopView desktopView){
        initComponents();
    }
    
    @Override
    public void initialiseView(){
        ArrayList<JCheckBox> checkBoxs = getOptions();
        
        Iterator<JCheckBox> iterator = getOptions().iterator();
        while(iterator.hasNext()){
            lstCheckBoxs.add(iterator.next());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCheckBoxs = new javax.swing.JList<>();

        lstCheckBoxs.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lstCheckBoxs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<JCheckBox> lstCheckBoxs;
    // End of variables declaration//GEN-END:variables
}
