/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package colinhewlettsolutions.client.view.views.modal_views;

/**
 *
 * @author colin
 */
public class TestPatientRecallDetailsEditorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form TestPatientRecallDetailsEditorView
     */
    public TestPatientRecallDetailsEditorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecallDate = new javax.swing.JPanel();
        dpsRecallDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        pnlRecallFrequency = new javax.swing.JPanel();
        spnRecallFrequency = new javax.swing.JSpinner();
        lblMonths = new javax.swing.JLabel();
        btnSaveDetails = new javax.swing.JButton();
        btnSaveDetails1 = new javax.swing.JButton();

        pnlRecallDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Recall date"));

        javax.swing.GroupLayout pnlRecallDateLayout = new javax.swing.GroupLayout(pnlRecallDate);
        pnlRecallDate.setLayout(pnlRecallDateLayout);
        pnlRecallDateLayout.setHorizontalGroup(
            pnlRecallDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecallDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpsRecallDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlRecallDateLayout.setVerticalGroup(
            pnlRecallDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecallDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpsRecallDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRecallFrequency.setBorder(javax.swing.BorderFactory.createTitledBorder("Recall frequency"));

        lblMonths.setText("months");

        javax.swing.GroupLayout pnlRecallFrequencyLayout = new javax.swing.GroupLayout(pnlRecallFrequency);
        pnlRecallFrequency.setLayout(pnlRecallFrequencyLayout);
        pnlRecallFrequencyLayout.setHorizontalGroup(
            pnlRecallFrequencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecallFrequencyLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(spnRecallFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMonths)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlRecallFrequencyLayout.setVerticalGroup(
            pnlRecallFrequencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecallFrequencyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecallFrequencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRecallFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonths))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSaveDetails.setText("Save");

        btnSaveDetails1.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRecallDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRecallFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveDetails)
                .addGap(43, 43, 43)
                .addComponent(btnSaveDetails1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRecallFrequency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRecallDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveDetails1)
                    .addComponent(btnSaveDetails))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDetails;
    private javax.swing.JButton btnSaveDetails1;
    private com.github.lgooddatepicker.components.DatePicker dpsRecallDatePicker;
    private javax.swing.JLabel lblMonths;
    private javax.swing.JPanel pnlRecallDate;
    private javax.swing.JPanel pnlRecallFrequency;
    private javax.swing.JSpinner spnRecallFrequency;
    // End of variables declaration//GEN-END:variables
}
