/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.views.non_modal_views;

import controller.ViewController;
import view.View;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author colin
 */
public class DataMigrationProgressView extends View {
    enum Mode {
        APPOINTMENT,
        PATIENT,  
        PATIENT_NOTE, 
        PRIMARY_CONDITION,
        SECONDARY_CONDITION,
        TREATMENT,
        NONE};
    enum Operation {EXPORT, IMPORT};
    
    private final boolean hasSystemGCed = false;
    private final static String IMPORT_TITLE_HEADER = "Data migration progress monitor";
    private final static String IMPORT_APPOINTMENT_PROGRESS_HEADER = 
            "Appointment table data migrated from CSV source";
    private final static String IMPORT_PATIENT_PROGRESS_HEADER = 
            "Patient table data migrated from CSV source";
    private final static String IMPORT_PRIMARY_CONDITION_PROGRESS_HEADER = 
            "PrimaryCondition table data migrated from SystemDefinition.xml template";
    private final static String IMPORT_SECONDARY_CONDITION_PROGRESS_HEADER = 
            "SecondaryCondition table data migrated from SystemDefinition.xml template";
    private final static String IMPORT_TREATMENT_PROGRESS_HEADER = 
            "Treatment table data migrated from SystemDefinition.xml template";
    /*28/03/2024private final static String IMPORT_PATIENT_NOTES_PROGRESS_HEADER = "PatientNotes table data migrated from appointment table";*/
    private final static String IMPORT_START_PROCESS_HEADER = "Start import";
    
    
    private Mode mode = Mode.NONE;
    private InternalFrameAdapter internalFrameAdapter = null;
    
    private void setMode(Mode value){
        mode = value;
    }
    
    private Mode getMode(){
        return mode;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPatients = new javax.swing.JProgressBar();
        lblPatientsProgressBar = new javax.swing.JLabel();
        lblAppointmentsProgressBar = new javax.swing.JLabel();
        barAppointments = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        barPrimaryCondition = new javax.swing.JProgressBar();
        lblPrimaryCondition = new javax.swing.JLabel();
        lblSecondaryCondition = new javax.swing.JLabel();
        barSecondaryCondition = new javax.swing.JProgressBar();
        lblTreatment = new javax.swing.JLabel();
        barTreatment = new javax.swing.JProgressBar();

        setTitle("Exported data progress");

        barPatients.setMinimum(0);
        barPatients.setStringPainted(true);

        barPatients.setMaximum(100);

        lblPatientsProgressBar.setText("Patients");

        lblAppointmentsProgressBar.setText("Appointments");

        barAppointments.setMinimum(0);
        barAppointments.setMaximum(100);
        barAppointments.setStringPainted(true);

        btnStart.setText("Start export");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnClose.setText("Close view");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        barPrimaryCondition.setMinimum(0);
        barPrimaryCondition.setMaximum(100);
        barPrimaryCondition.setStringPainted(true);

        lblPrimaryCondition.setText("PrimaryCondition");

        lblSecondaryCondition.setText("SecondaryCondition");

        barSecondaryCondition.setMinimum(0);
        barSecondaryCondition.setMaximum(100);
        barSecondaryCondition.setStringPainted(true);

        lblTreatment.setText("Treatment");

        barSecondaryCondition.setMinimum(0);
        barSecondaryCondition.setMaximum(100);
        barSecondaryCondition.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barPatients, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                            .addComponent(barAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barPrimaryCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barSecondaryCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientsProgressBar)
                                    .addComponent(lblAppointmentsProgressBar)
                                    .addComponent(lblPrimaryCondition)
                                    .addComponent(lblSecondaryCondition))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addGap(79, 79, 79)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTreatment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPatientsProgressBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAppointmentsProgressBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrimaryCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPrimaryCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSecondaryCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barSecondaryCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblTreatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        try{
            setClosed(true);
        }catch (PropertyVetoException ex){
            
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnStart.setEnabled(false);
        ActionEvent actionEvent = new ActionEvent(this, 
                ActionEvent.ACTION_PERFORMED,
                ViewController.DataMigrationViewControllerActionEvent.DATA_MIGRATION_START_REQUEST.toString());
        getMyController().actionPerformed(actionEvent);
        

    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barAppointments;
    private javax.swing.JProgressBar barPatients;
    private javax.swing.JProgressBar barPrimaryCondition;
    private javax.swing.JProgressBar barSecondaryCondition;
    private javax.swing.JProgressBar barTreatment;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblAppointmentsProgressBar;
    private javax.swing.JLabel lblPatientsProgressBar;
    private javax.swing.JLabel lblPrimaryCondition;
    private javax.swing.JLabel lblSecondaryCondition;
    private javax.swing.JLabel lblTreatment;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public DataMigrationProgressView(
            View.Viewer myViewType,
            ViewController myController,
            DesktopView desktopView) {
        setTitle("Data importer view");
        setDesktopView(desktopView);
        setMyViewType(myViewType);
        setMyController(myController);
        initComponents();
        this.setVisible(true);
        addInternalFrameListeners();
        lblPatientsProgressBar.setText(DataMigrationProgressView.IMPORT_PATIENT_PROGRESS_HEADER);
        lblAppointmentsProgressBar.setText(DataMigrationProgressView.IMPORT_APPOINTMENT_PROGRESS_HEADER);
        this.lblPrimaryCondition.setText(IMPORT_PRIMARY_CONDITION_PROGRESS_HEADER);
        this.lblSecondaryCondition.setText(IMPORT_SECONDARY_CONDITION_PROGRESS_HEADER);
        this.lblTreatment.setText(IMPORT_TREATMENT_PROGRESS_HEADER);
        /*28/03/2024lblPatientNotesProgressBar.setText(DataMigrationProgressView.IMPORT_PATIENT_NOTES_PROGRESS_HEADER);*/
        btnStart.setText(DataMigrationProgressView.IMPORT_START_PROCESS_HEADER);
        this.setTitle(DataMigrationProgressView.IMPORT_TITLE_HEADER);
    }

    public void addInternalFrameListeners(){
        /**
         * Establish an InternalFrameListener for when the view is closed 
         */
        
        internalFrameAdapter = new InternalFrameAdapter(){
            @Override  
            public void internalFrameClosing(InternalFrameEvent e) {
                ActionEvent actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.DATA_MIGRATION_PROGRESS_VIEW_CLOSE_NOTIFICATION.toString());
                getMyController().actionPerformed(actionEvent);
            }
        };
        this.addInternalFrameListener(internalFrameAdapter);
    }

    @Override
    public void initialiseView(){
        
        this.setVisible(true);
        //lblPatientsProgressBar.setText(DataMigrationProgressView.IMPORT_PATIENT_PROGRESS_HEADER);
        //lblAppointmentsProgressBar.setText(DataMigrationProgressView.IMPORT_APPOINTMENT_PROGRESS_HEADER);
        btnStart.setText(DataMigrationProgressView.IMPORT_START_PROCESS_HEADER);
        this.setTitle(DataMigrationProgressView.IMPORT_TITLE_HEADER);
        this.setSize(520,350);
    }
    
    /**
     * the source of property change events to the listener are twofold
     * -- the SwingWorker class fires two kinds of event on the change in value of two bound variables
     * ---- progress; which is used in the VC to signify the percentage of Appointment of Patient records imported imported
     * ---- state; which is not used by the listener
     * -- the VC independently of the SwingWorker class fires 3 property change events
     * ---- OPERATION_COMPLETED
     * ---- PREPARE_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS
     * ---- PREPARE_FOR_RECEIPT_OF_PATIENT_PROGRESS
     * 
     * @param e 
     */
    @Override
    public void propertyChange(PropertyChangeEvent e){
        switch(e.getPropertyName()){
            case "progress":
                int progress = (Integer) e.getNewValue();
                switch (getMode()){
                    case PATIENT:
                        barPatients.setIndeterminate(false);
                        barPatients.setValue(progress);
                        break;
                    case APPOINTMENT:
                        barAppointments.setIndeterminate(false);
                        barAppointments.setValue(progress);
                        break;
                    case PATIENT_NOTE:
                        //barPatientNotes.setIndeterminate(false);
                        //barPatientNotes.setValue(progress);
                        break;
                    case PRIMARY_CONDITION:
                        barPrimaryCondition.setIndeterminate(false);
                        barPrimaryCondition.setValue(progress);
                        break;
                    case SECONDARY_CONDITION:
                        barSecondaryCondition.setIndeterminate(false);
                        barSecondaryCondition.setValue(progress);
                        break;
                    case TREATMENT:
                        barTreatment.setIndeterminate(false);
                        barTreatment.setValue(progress);
                        break;
                }
                break;
            case "state":
                break;
        }
        ActionEvent actionEvent = null;
        ViewController.DataMigrationViewControllerPropertyChangeEvent propertyName =
                ViewController.DataMigrationViewControllerPropertyChangeEvent.valueOf(e.getPropertyName());
        switch(propertyName){    
            case DATA_MIGRATION_COMPLETED:
                btnStart.setEnabled(true);
                setMode(Mode.NONE);
                break;    
            case PREPARE_FOR_RECEIPT_OF_APPOINTMENT_MIGRATION_PROGRESS:
                barAppointments.setIndeterminate(true);
                barAppointments.setValue(0);
                setMode(Mode.APPOINTMENT);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_APPOINTMENT_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;  
            case PREPARE_FOR_RECEIPT_OF_PATIENT_NOTE_MIGRATION_PROGRESS:
                //barPatientNotes.setIndeterminate(true);
                //barPatientNotes.setValue(0);
                setMode(Mode.PATIENT_NOTE);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_PATIENT_NOTE_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;  
            case PREPARE_FOR_RECEIPT_OF_PATIENT_MIGRATION_PROGRESS:
                barPatients.setIndeterminate(true);
                barPatients.setValue(0);
                setMode(Mode.PATIENT);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_PATIENT_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
            case PREPARE_FOR_RECEIPT_OF_PRIMARY_CONDITION_MIGRATION_PROGRESS:
                barPrimaryCondition.setIndeterminate(true);
                barPrimaryCondition.setValue(0);
                setMode(Mode.PRIMARY_CONDITION);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_PRIMARY_CONDITION_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
            case PREPARE_FOR_RECEIPT_OF_SECONDARY_CONDITION_MIGRATION_PROGRESS:
                barSecondaryCondition.setIndeterminate(true);
                barSecondaryCondition.setValue(0);
                setMode(Mode.SECONDARY_CONDITION);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_SECONDARY_CONDITION_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
            case PREPARE_FOR_RECEIPT_OF_TREATMENT_MIGRATION_PROGRESS:
                barTreatment.setIndeterminate(true);
                barTreatment.setValue(0);
                setMode(Mode.TREATMENT);
                actionEvent = new ActionEvent(
                        DataMigrationProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.DataMigrationViewControllerActionEvent.READY_FOR_RECEIPT_OF_TREATMENT_MIGRATION_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
        }

    }

}
