/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.views.non_modal_views;

import controller.ViewController;
import view.View;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author colin
 */
public class ImportProgressView extends View {
    enum Mode {PATIENT, APPOINTMENT, PATIENT_NOTE, NONE};
    enum Operation {EXPORT, IMPORT};
    
    private final boolean hasSystemGCed = false;
    private final static String IMPORT_TITLE_HEADER = "Import progress";
    private final static String IMPORT_APPOINTMENT_PROGRESS_HEADER = "Import appointment data from CSV source";
    private final static String IMPORT_PATIENT_PROGRESS_HEADER = "Import patient data from CSV source";
    private final static String IMPORT_PATIENT_NOTES_PROGRESS_HEADER = "Import patient notes data from appointment data";
    private final static String IMPORT_START_PROCESS_HEADER = "Start import";
    
    
    private Mode mode = Mode.NONE;
    private InternalFrameAdapter internalFrameAdapter = null;
    
    private void setMode(Mode value){
        mode = value;
    }
    
    private Mode getMode(){
        return mode;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPatients = new javax.swing.JProgressBar();
        lblPatientsProgressBar = new javax.swing.JLabel();
        lblAppointmentsProgressBar = new javax.swing.JLabel();
        barAppointments = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblPatientNotesProgressBar = new javax.swing.JLabel();
        barPatientNotes = new javax.swing.JProgressBar();

        setTitle("Exported data progress");

        barPatients.setMinimum(0);
        barPatients.setStringPainted(true);

        barPatients.setMaximum(100);

        lblPatientsProgressBar.setText("Patients");

        lblAppointmentsProgressBar.setText("Appointments");

        barAppointments.setMinimum(0);
        barAppointments.setMaximum(100);
        barAppointments.setStringPainted(true);

        btnStart.setText("Start export");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnClose.setText("Close view");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblPatientNotesProgressBar.setText("PatientNotes");

        barPatientNotes.setMinimum(0);
        barPatientNotes.setMaximum(100);
        barPatientNotes.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(barPatientNotes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientsProgressBar)
                            .addComponent(lblAppointmentsProgressBar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(barAppointments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(barPatients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblPatientNotesProgressBar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPatientsProgressBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lblAppointmentsProgressBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPatientNotesProgressBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPatientNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        try{
            setClosed(true);
        }catch (PropertyVetoException ex){
            
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnStart.setEnabled(false);
        ActionEvent actionEvent = new ActionEvent(this, 
                ActionEvent.ACTION_PERFORMED,
                ViewController.ImportProgressViewControllerActionEvent.IMPORT_EXPORT_START_REQUEST.toString());
        getMyController().actionPerformed(actionEvent);
        

    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barAppointments;
    private javax.swing.JProgressBar barPatientNotes;
    private javax.swing.JProgressBar barPatients;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblAppointmentsProgressBar;
    private javax.swing.JLabel lblPatientNotesProgressBar;
    private javax.swing.JLabel lblPatientsProgressBar;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ImportProgressView(
            View.Viewer myViewType,
            ViewController myController,
            DesktopView desktopView) {
        setTitle("Data importer view");
        setDesktopView(desktopView);
        setMyViewType(myViewType);
        setMyController(myController);
        initComponents();
        this.setVisible(true);
        addInternalFrameListeners();
        lblPatientsProgressBar.setText(ImportProgressView.IMPORT_PATIENT_PROGRESS_HEADER);
        lblAppointmentsProgressBar.setText(ImportProgressView.IMPORT_APPOINTMENT_PROGRESS_HEADER);
        lblPatientNotesProgressBar.setText(ImportProgressView.IMPORT_PATIENT_NOTES_PROGRESS_HEADER);
        btnStart.setText(ImportProgressView.IMPORT_START_PROCESS_HEADER);
        this.setTitle(ImportProgressView.IMPORT_TITLE_HEADER);
    }

    public void addInternalFrameListeners(){
        /**
         * Establish an InternalFrameListener for when the view is closed 
         */
        
        internalFrameAdapter = new InternalFrameAdapter(){
            @Override  
            public void internalFrameClosing(InternalFrameEvent e) {
                ActionEvent actionEvent = new ActionEvent(
                        ImportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.ImportProgressViewControllerActionEvent.IMPORT_EXPORT_PROGRESS_CLOSE_NOTIFICATION.toString());
                getMyController().actionPerformed(actionEvent);
            }
        };
        this.addInternalFrameListener(internalFrameAdapter);
    }

    @Override
    public void initialiseView(){
        
        this.setVisible(true);
        lblPatientsProgressBar.setText(ImportProgressView.IMPORT_PATIENT_PROGRESS_HEADER);
        lblAppointmentsProgressBar.setText(ImportProgressView.IMPORT_APPOINTMENT_PROGRESS_HEADER);
        btnStart.setText(ImportProgressView.IMPORT_START_PROCESS_HEADER);
        this.setTitle(ImportProgressView.IMPORT_TITLE_HEADER);
    }
    
    /**
     * the source of property change events to the listener are twofold
     * -- the SwingWorker class fires two kinds of event on the change in value of two bound variables
     * ---- progress; which is used in the VC to signify the percentage of Appointment of Patient records imported imported
     * ---- state; which is not used by the listener
     * -- the VC independently of the SwingWorker class fires 3 property change events
     * ---- OPERATION_COMPLETED
     * ---- PREPARE_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS
     * ---- PREPARE_FOR_RECEIPT_OF_PATIENT_PROGRESS
     * 
     * @param e 
     */
    @Override
    public void propertyChange(PropertyChangeEvent e){
        switch(e.getPropertyName()){
            case "progress":
                int progress = (Integer) e.getNewValue();
                switch (getMode()){
                    case PATIENT:
                        barPatients.setIndeterminate(false);
                        barPatients.setValue(progress);
                        break;
                    case APPOINTMENT:
                        barAppointments.setIndeterminate(false);
                        barAppointments.setValue(progress);
                        break;
                    case PATIENT_NOTE:
                        barPatientNotes.setIndeterminate(false);
                        barPatientNotes.setValue(progress);
                        break;
                }
                break;
            case "state":
                break;
        }
        ActionEvent actionEvent = null;
        ViewController.ImportProgressViewControllerPropertyChangeEvent propertyName =
                ViewController.ImportProgressViewControllerPropertyChangeEvent.valueOf(e.getPropertyName());
        switch(propertyName){    
            case OPERATION_COMPLETED:
                btnStart.setEnabled(true);
                setMode(Mode.NONE);
                break;    
            case PREPARE_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS:
                barAppointments.setIndeterminate(true);
                barAppointments.setValue(0);
                setMode(Mode.APPOINTMENT);
                actionEvent = new ActionEvent(
                        ImportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.ImportProgressViewControllerActionEvent.READY_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;  
            case PREPARE_FOR_RECEIPT_OF_PATIENT_NOTE_PROGRESS:
                barPatientNotes.setIndeterminate(true);
                barPatientNotes.setValue(0);
                setMode(Mode.PATIENT_NOTE);
                actionEvent = new ActionEvent(
                        ImportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.ImportProgressViewControllerActionEvent.READY_FOR_RECEIPT_OF_PATIENT_NOTE_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;  
            case PREPARE_FOR_RECEIPT_OF_PATIENT_PROGRESS:
                barPatients.setIndeterminate(true);
                barPatients.setValue(0);
                setMode(Mode.PATIENT);
                actionEvent = new ActionEvent(
                        ImportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        ViewController.ImportProgressViewControllerActionEvent.READY_FOR_RECEIPT_OF_PATIENT_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
        }

    }

}
