/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.views.non_modal_views;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;
import model.non_entity.SystemDefinition;
import view.View;

/**
 *
 * @author colin
 */
public class UserColorSettingsView extends View 
        implements ActionListener, PropertyChangeListener{
    
    public enum Action{
        DIARY_BOOKING_FIRST_ROW_COLOR_REQUEST,
        DIARY_BOOKING_REMAINING_ROWS_COLOR_REQUEST,
        DIARY_BOOKABLE_SLOT_COLOR_REQUEST,
        DIARY_SCHEDULE_VIEW_FACTORY_SETTINGS_REQUEST,
        LIST_EMERGENCY_BOOKING_TEXT_COLOR_REQUEST,
        LIST_BOOKABLE_SLOT_TEXT_COLOR_REQUEST,
        LIST_UNBOOKABLE_SLOT_TEXT_COLOR_REQUEST,
        LIST_SCHEDULE_VIEW_FACTORY_SETTINGS_REQUEST,
        TITLED_BORDER_COLOR_REQUEST,
        TITLED_BORDER_FACTORY_SETTINGS_REQUEST
    }

    /**
     * Creates new form UserColorSettingsView
     */
    public UserColorSettingsView() {
        initComponents();
    }
    
    public void actionPerformed (ActionEvent e){
        Action action = Action.valueOf(e.getActionCommand());
        switch(action){
            case DIARY_BOOKING_FIRST_ROW_COLOR_REQUEST:
                break;
            case DIARY_BOOKING_REMAINING_ROWS_COLOR_REQUEST:
                break;
            case DIARY_BOOKABLE_SLOT_COLOR_REQUEST:
                break;
            case DIARY_SCHEDULE_VIEW_FACTORY_SETTINGS_REQUEST:
                break;
            case LIST_EMERGENCY_BOOKING_TEXT_COLOR_REQUEST:
                break;
            case LIST_BOOKABLE_SLOT_TEXT_COLOR_REQUEST:
                break;
            case LIST_UNBOOKABLE_SLOT_TEXT_COLOR_REQUEST:
                break;
            case LIST_SCHEDULE_VIEW_FACTORY_SETTINGS_REQUEST:
                break;
            case TITLED_BORDER_COLOR_REQUEST:
                break;
            case TITLED_BORDER_FACTORY_SETTINGS_REQUEST:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlScheduleDiaryBackgroundColor = new javax.swing.JPanel();
        btnDiaryBookingFirstRow = new javax.swing.JButton();
        btnDiaryBookingRemainingRows = new javax.swing.JButton();
        btnDiaryUnbookable = new javax.swing.JButton();
        lblDiaryBookingFirstRow = new javax.swing.JLabel();
        lblDiaryBookingRemainingRows = new javax.swing.JLabel();
        lblDiaryUnbookableSlot = new javax.swing.JLabel();
        btnDiaryScheduleViewFactorySettings = new javax.swing.JButton();
        pnlScheduleDiaryBackgroundColour = new javax.swing.JPanel();
        btnListEmergencyBookingText = new javax.swing.JButton();
        btnListBookableSlotText = new javax.swing.JButton();
        lblListEmergencyBookingText = new javax.swing.JLabel();
        lblListBookableSlotText = new javax.swing.JLabel();
        btnListUnbookableSlotText = new javax.swing.JButton();
        lblListUnbookableSlotText = new javax.swing.JLabel();
        btnListScheduleViewFactorySettings = new javax.swing.JButton();
        pnlTitledBorderColor = new javax.swing.JPanel();
        btnTitledBorder = new javax.swing.JButton();
        btnAllViewsTitledBorderFactorySettings = new javax.swing.JButton();
        lblTitledBorder = new javax.swing.JLabel();

        pnlScheduleDiaryBackgroundColor.setBorder(javax.swing.BorderFactory.createTitledBorder("Schedule diary view background colour"));

        btnDiaryBookingFirstRow.setText("First row of booking");

        btnDiaryBookingRemainingRows.setText("Remaining rows of booking");

        btnDiaryUnbookable.setText("Bookable slot");

        lblDiaryBookingFirstRow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDiaryBookingRemainingRows.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDiaryUnbookableSlot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDiaryScheduleViewFactorySettings.setText("Factory settings");

        javax.swing.GroupLayout pnlScheduleDiaryBackgroundColorLayout = new javax.swing.GroupLayout(pnlScheduleDiaryBackgroundColor);
        pnlScheduleDiaryBackgroundColor.setLayout(pnlScheduleDiaryBackgroundColorLayout);
        pnlScheduleDiaryBackgroundColorLayout.setHorizontalGroup(
            pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDiaryBackgroundColorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDiaryScheduleViewFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiaryUnbookable, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiaryBookingRemainingRows, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiaryBookingFirstRow, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaryBookingFirstRow, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaryBookingRemainingRows, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaryUnbookableSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlScheduleDiaryBackgroundColorLayout.setVerticalGroup(
            pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDiaryBackgroundColorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDiaryBookingFirstRow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaryBookingFirstRow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDiaryBookingRemainingRows, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaryBookingRemainingRows, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlScheduleDiaryBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiaryUnbookable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaryUnbookableSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDiaryScheduleViewFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlScheduleDiaryBackgroundColour.setBorder(javax.swing.BorderFactory.createTitledBorder("Schedule list view text colour options"));

        btnListEmergencyBookingText.setText("Emergency booking text colour");

        btnListBookableSlotText.setText("Bookable slot text colour");

        lblListEmergencyBookingText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblListBookableSlotText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnListUnbookableSlotText.setText("Unbookable slot text colour");

        lblListUnbookableSlotText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnListScheduleViewFactorySettings.setText("Factory settings");

        javax.swing.GroupLayout pnlScheduleDiaryBackgroundColourLayout = new javax.swing.GroupLayout(pnlScheduleDiaryBackgroundColour);
        pnlScheduleDiaryBackgroundColour.setLayout(pnlScheduleDiaryBackgroundColourLayout);
        pnlScheduleDiaryBackgroundColourLayout.setHorizontalGroup(
            pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                        .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListUnbookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListScheduleViewFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(lblListUnbookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                        .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListBookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListEmergencyBookingText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListEmergencyBookingText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblListBookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlScheduleDiaryBackgroundColourLayout.setVerticalGroup(
            pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListEmergencyBookingText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListEmergencyBookingText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListBookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListBookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlScheduleDiaryBackgroundColourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                        .addComponent(lblListUnbookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlScheduleDiaryBackgroundColourLayout.createSequentialGroup()
                        .addComponent(btnListUnbookableSlotText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListScheduleViewFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        pnlTitledBorderColor.setBorder(javax.swing.BorderFactory.createTitledBorder("All views"));

        btnTitledBorder.setText("Panel titled border text colour");

        btnAllViewsTitledBorderFactorySettings.setText("Factory settings");

        lblTitledBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlTitledBorderColorLayout = new javax.swing.GroupLayout(pnlTitledBorderColor);
        pnlTitledBorderColor.setLayout(pnlTitledBorderColorLayout);
        pnlTitledBorderColorLayout.setHorizontalGroup(
            pnlTitledBorderColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitledBorderColorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlTitledBorderColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAllViewsTitledBorderFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitledBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lblTitledBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlTitledBorderColorLayout.setVerticalGroup(
            pnlTitledBorderColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitledBorderColorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlTitledBorderColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTitledBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitledBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAllViewsTitledBorderFactorySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScheduleDiaryBackgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTitledBorderColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlScheduleDiaryBackgroundColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlScheduleDiaryBackgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlScheduleDiaryBackgroundColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(pnlTitledBorderColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllViewsTitledBorderFactorySettings;
    private javax.swing.JButton btnDiaryBookingFirstRow;
    private javax.swing.JButton btnDiaryBookingRemainingRows;
    private javax.swing.JButton btnDiaryScheduleViewFactorySettings;
    private javax.swing.JButton btnDiaryUnbookable;
    private javax.swing.JButton btnListBookableSlotText;
    private javax.swing.JButton btnListEmergencyBookingText;
    private javax.swing.JButton btnListScheduleViewFactorySettings;
    private javax.swing.JButton btnListUnbookableSlotText;
    private javax.swing.JButton btnTitledBorder;
    private javax.swing.JLabel lblDiaryBookingFirstRow;
    private javax.swing.JLabel lblDiaryBookingRemainingRows;
    private javax.swing.JLabel lblDiaryUnbookableSlot;
    private javax.swing.JLabel lblListBookableSlotText;
    private javax.swing.JLabel lblListEmergencyBookingText;
    private javax.swing.JLabel lblListUnbookableSlotText;
    private javax.swing.JLabel lblTitledBorder;
    private javax.swing.JPanel pnlScheduleDiaryBackgroundColor;
    private javax.swing.JPanel pnlScheduleDiaryBackgroundColour;
    private javax.swing.JPanel pnlTitledBorderColor;
    // End of variables declaration//GEN-END:variables
}
