/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.views.modal_views;

import controller.ViewController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.beans.PropertyVetoException;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import model.TreatmentWithState;
import view.View;
import view.views.non_modal_views.DesktopView;
import view.views.view_support_classes.models.TreatmentWithStateTableModel;
/**
 *
 * @author colin
 */
public class ModalAppointmentTreatmentView extends ModalView 
        implements ActionListener, TableModelListener {

    enum Action {
        REQUEST_CLOSE_VIEW
    }
    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalAppointmentTreatmentView(View.Viewer myViewType, 
            ViewController myController,
            DesktopView desktopView) {//ViewMode arg
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);  
    } 
    
    public void actionPerformed(ActionEvent e){
        switch (Action.valueOf(e.getActionCommand())){
            case REQUEST_CLOSE_VIEW:
                try{
                    this.setClosed(true);   
                }catch (PropertyVetoException ex){
                    
                }
                break;
        }
    }
    
    public void tableChanged(TableModelEvent e){
        ViewController.ScheduleViewControllerActionEvent actionCommand = null;
        TreatmentWithState treatmentWithState = null;
        int row = e.getFirstRow();
        int column = e.getColumn();
        TreatmentWithStateTableModel model =  
                (TreatmentWithStateTableModel)e.getSource();
        Boolean value = (Boolean)model.getValueAt(row, column);
        treatmentWithState = (TreatmentWithState)model.getElementAt(row);
        treatmentWithState.setState(value);
        getMyController().getDescriptor().getViewDescription().setTreatmentWithState(treatmentWithState);
        tblTreatmentWithState.clearSelection();
        if (treatmentWithState.getState())
            actionCommand = ViewController.ScheduleViewControllerActionEvent
                    .APPOINTMENT_TREATMENT_STATE_SET_REQUEST;
        else actionCommand = ViewController.ScheduleViewControllerActionEvent
                    .APPOINTMENT_TREATMENT_STATE_RESET_REQUEST;
        
        ActionEvent actionEvent = new ActionEvent(
            this,ActionEvent.ACTION_PERFORMED,
            actionCommand.toString());
        getMyController().actionPerformed(actionEvent);
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        this.setClosable(true);
        setTitle("Appointment treatment options");
        btnClose.setActionCommand(Action.REQUEST_CLOSE_VIEW.toString());
        btnClose.addActionListener(this);
        setVisible(true);
        setSize(266, 432);
        populateTreatmentTable();
    }
    
    private void populateTreatmentTable(){
        ArrayList<TreatmentWithState> treatmentsWithState = new ArrayList<>();
        TreatmentWithStateTableModel model = 
                (TreatmentWithStateTableModel)this.tblTreatmentWithState.getModel();
        model.removeAllElements();
        treatmentsWithState = getMyController().getDescriptor()
                .getControllerDescription().getTreatmentWithState().get();
        Iterator it = treatmentsWithState.iterator();
        while(it.hasNext()){
            TreatmentWithState tws = (TreatmentWithState)it.next();
            model.addElement(tws);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTreatmentTable = new javax.swing.JPanel();
        scrTreatment = new javax.swing.JScrollPane();
        tblTreatmentWithState = new javax.swing.JTable();
        pnlCloseButton = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        tblTreatmentWithState.setModel(new TreatmentWithStateTableModel());
        tblTreatmentWithState.getModel().addTableModelListener(this);
        scrTreatment.setViewportView(tblTreatmentWithState);
        ViewController.setJTableColumnProperties(
            tblTreatmentWithState, scrTreatment.getPreferredSize().width, 20,80);

        javax.swing.GroupLayout pnlTreatmentTableLayout = new javax.swing.GroupLayout(pnlTreatmentTable);
        pnlTreatmentTable.setLayout(pnlTreatmentTableLayout);
        pnlTreatmentTableLayout.setHorizontalGroup(
            pnlTreatmentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlTreatmentTableLayout.setVerticalGroup(
            pnlTreatmentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        btnClose.setText("Close view");

        javax.swing.GroupLayout pnlCloseButtonLayout = new javax.swing.GroupLayout(pnlCloseButton);
        pnlCloseButton.setLayout(pnlCloseButtonLayout);
        pnlCloseButtonLayout.setHorizontalGroup(
            pnlCloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCloseButtonLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlCloseButtonLayout.setVerticalGroup(
            pnlCloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCloseButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTreatmentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTreatmentTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel pnlCloseButton;
    private javax.swing.JPanel pnlTreatmentTable;
    private javax.swing.JScrollPane scrTreatment;
    private javax.swing.JTable tblTreatmentWithState;
    // End of variables declaration//GEN-END:variables
}
