/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.views.modal_views;

/**
 *
 * @author colin
 */
public class ModalToDoEditorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModalToDoEditorView
     */
    public ModalToDoEditorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker dpToDoDate;
    private com.github.lgooddatepicker.components.DatePicker dpToDoDate1;
    private com.github.lgooddatepicker.components.DatePicker dpToDoDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlRadioButtons;
    private javax.swing.JPanel pnlRadioButtons1;
    private javax.swing.JPanel pnlRadioButtons2;
    private javax.swing.JPanel pnlToDoDetails;
    private javax.swing.JPanel pnlToDoDetails1;
    private javax.swing.JPanel pnlToDoDetails2;
    private javax.swing.JRadioButton rdbToDoActioned;
    private javax.swing.JRadioButton rdbToDoActioned1;
    private javax.swing.JRadioButton rdbToDoActioned2;
    private javax.swing.JRadioButton rdbToDoUnactioned;
    private javax.swing.JRadioButton rdbToDoUnactioned1;
    private javax.swing.JRadioButton rdbToDoUnactioned2;
    private javax.swing.JTextArea txaToDoDescription;
    private javax.swing.JTextArea txaToDoDescription1;
    private javax.swing.JTextArea txaToDoDescription2;
    // End of variables declaration//GEN-END:variables
}
