/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.views.modal_views;

import controller.ViewController;
import view.View;
import view.views.non_modal_views.DesktopView;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map.Entry;

import javax.swing.JOptionPane;

import java.time.DayOfWeek;

/**
 *
 * @author colin
 */
public class ModalSurgeryDaysEditorView extends ModalView {

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalSurgeryDaysEditorView(
            View.Viewer myViewType, 
            ViewController myController, 
            DesktopView  desktopView) {//ViewMode arg
        setTitle("Surgery days editor");
        setMyViewType(myViewType);
        setMyController(myController);
        setDesktopView(desktopView);
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        this.setVisible(true);
        this.setClosable(true);

        HashMap<DayOfWeek, Boolean> surgeryDays = getMyController().
                getDescriptor().getControllerDescription().getSurgeryDaysAssignment();
        for(Entry<DayOfWeek,Boolean> entry : surgeryDays.entrySet()){
            switch(entry.getKey()){
                case MONDAY:
                    this.chkMonday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case TUESDAY:
                    this.chkTuesday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case WEDNESDAY:
                    this.chkWednesday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case THURSDAY:
                    this.chkThursday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case FRIDAY:
                    this.chkFriday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case SATURDAY:
                    this.chkSaturday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
                case SUNDAY:
                    this.chkSunday.setSelected(surgeryDays.get(entry.getKey()));
                    break;
            }
        }
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent e){
        //setViewDescriptor((Descriptor)e.getNewValue());
 
        if (e.getPropertyName().equals(
            ViewController.ScheduleViewControllerPropertyChangeEvent.APPOINTMENT_SCHEDULE_ERROR_RECEIVED.toString())){
            ViewController.displayErrorMessage(getMyController().getDescriptor().
                    getControllerDescription().getError(),
                                               "Appointment editor dialog error",
                                               JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkTuesday = new javax.swing.JCheckBox();
        chkMonday = new javax.swing.JCheckBox();
        chkWednesday = new javax.swing.JCheckBox();
        chkThursday = new javax.swing.JCheckBox();
        chkFriday = new javax.swing.JCheckBox();
        chkSaturday = new javax.swing.JCheckBox();
        chkSunday = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chkTuesday.setText("Tuesday");

        chkMonday.setText("Monday");

        chkWednesday.setText("Wednesday");

        chkThursday.setText("Thursday");

        chkFriday.setText("Friday");

        chkSaturday.setText("Saturday");

        chkSunday.setText("Sunday");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSunday)
                    .addComponent(chkSaturday)
                    .addComponent(chkFriday)
                    .addComponent(chkThursday)
                    .addComponent(chkWednesday)
                    .addComponent(chkMonday)
                    .addComponent(chkTuesday))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkMonday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTuesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkWednesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkThursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFriday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSaturday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSunday)
                .addGap(20, 20, 20))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        HashMap<DayOfWeek,Boolean> surgeryDaysAssignmentValue = new HashMap<DayOfWeek,Boolean>();
        surgeryDaysAssignmentValue.put(DayOfWeek.MONDAY, this.chkMonday.isSelected());
        surgeryDaysAssignmentValue.put(DayOfWeek.TUESDAY, this.chkTuesday.isSelected());
        surgeryDaysAssignmentValue.put(DayOfWeek.WEDNESDAY, this.chkWednesday.isSelected());
        surgeryDaysAssignmentValue.put(DayOfWeek.THURSDAY, this.chkThursday.isSelected());
        surgeryDaysAssignmentValue.put(DayOfWeek.FRIDAY, this.chkFriday.isSelected());
        surgeryDaysAssignmentValue.put(DayOfWeek.SATURDAY, this.chkSaturday.isSelected()); 
        surgeryDaysAssignmentValue.put(DayOfWeek.SUNDAY, this.chkSunday.isSelected());
        getMyController().getDescriptor().getViewDescription().
                setSurgeryDaysAssignmentValue(surgeryDaysAssignmentValue);
        
        ActionEvent actionEvent = new ActionEvent(this, 
                ActionEvent.ACTION_PERFORMED,
                ViewController.ScheduleViewControllerActionEvent.SURGERY_DAYS_EDIT_REQUEST.toString());
        this.getMyController().actionPerformed(actionEvent);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        try{
            this.setClosed(true);
        }
        catch (PropertyVetoException ex){
            
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkFriday;
    private javax.swing.JCheckBox chkMonday;
    private javax.swing.JCheckBox chkSaturday;
    private javax.swing.JCheckBox chkSunday;
    private javax.swing.JCheckBox chkThursday;
    private javax.swing.JCheckBox chkTuesday;
    private javax.swing.JCheckBox chkWednesday;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
