/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.views.modal_views;

import controller.ViewController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import model.entity.Appointment;
import model.entity.Patient;
import view.View;
import view.views.non_modal_views.DesktopView;
import view.support_classes.models.CancelledAppointmentsTableModel;
import view.support_classes.renderers.AppointmentsTableDurationRenderer;
import view.support_classes.renderers.AppointmentsTableLocalDateRenderer;
import view.support_classes.renderers.CancelledAppointmentsTablePatientRenderer;
import view.support_classes.renderers.TableHeaderCellBorderRenderer;

/**
 *
 * @author colin
 */
public class ModalCancelledAppointmentsView extends ModalView {
    //private JTable tblCancelledAppointments = null;
    private JScrollPane jScrollPane = null;

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalCancelledAppointmentsView(
        View.Viewer myViewType, 
        ViewController myController, 
        DesktopView desktopView){

        setTitle("Cancelled appointments view");
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        setSize(getWidth()+10, getHeight());
        this.populateCancelledAppointmentsTable();

        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  /*  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoToScheduleForSelectedAppointment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlOperations = new javax.swing.JPanel();
        btnUncancelSelectedAppointment = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();
        pnlCancelledAppointments = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCancelledAppointments = new javax.swing.JTable();

        btnGoToScheduleForSelectedAppointment.setText("Return to schedule for selected apoointment");
        btnGoToScheduleForSelectedAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToScheduleForSelectedAppointmentActionPerformed(evt);
            }
        });

        pnlOperations.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnUncancelSelectedAppointment.setText("Uncancel selected appointment");
        btnUncancelSelectedAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUncancelSelectedAppointmentActionPerformed(evt);
            }
        });

        btnCloseView.setText("Close view");
        btnCloseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperationsLayout = new javax.swing.GroupLayout(pnlOperations);
        pnlOperations.setLayout(pnlOperationsLayout);
        pnlOperationsLayout.setHorizontalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnUncancelSelectedAppointment)
                .addGap(77, 77, 77)
                .addComponent(btnCloseView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOperationsLayout.setVerticalGroup(
            pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUncancelSelectedAppointment)
                    .addComponent(btnCloseView))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pnlCancelledAppointments.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCancelledAppointments.setModel(new CancelledAppointmentsTableModel());
        TableColumnModel columnModel = this.tblCancelledAppointments.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(190);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(4).setPreferredWidth(105);
        columnModel.getColumn(0).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(1).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(2).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(3).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(4).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        JTableHeader tableHeader = this.tblCancelledAppointments.getTableHeader();
        tableHeader.setBackground(new Color(220,220,220));
        tableHeader.setOpaque(true);
        jScrollPane2.setViewportView(tblCancelledAppointments);

        javax.swing.GroupLayout pnlCancelledAppointmentsLayout = new javax.swing.GroupLayout(pnlCancelledAppointments);
        pnlCancelledAppointments.setLayout(pnlCancelledAppointmentsLayout);
        pnlCancelledAppointmentsLayout.setHorizontalGroup(
            pnlCancelledAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        pnlCancelledAppointmentsLayout.setVerticalGroup(
            pnlCancelledAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCancelledAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCancelledAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGoToScheduleForSelectedAppointment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlOperations = new javax.swing.JPanel();
        btnUncancelSelectedAppointment = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();
        pnlCancelledAppointments = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCancelledAppointments = new javax.swing.JTable();

        btnGoToScheduleForSelectedAppointment.setText("Return to schedule for selected apoointment");
        btnGoToScheduleForSelectedAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToScheduleForSelectedAppointmentActionPerformed(evt);
            }
        });

        pnlOperations.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnUncancelSelectedAppointment.setText("Uncancel selected appointment");
        btnUncancelSelectedAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUncancelSelectedAppointmentActionPerformed(evt);
            }
        });

        btnCloseView.setText("Close view");
        btnCloseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(pnlOperations);
        pnlOperations.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40)
                .addComponent(btnUncancelSelectedAppointment)
                .addGap(60)
                .addComponent(btnCloseView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUncancelSelectedAppointment)
                    .addComponent(btnCloseView))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pnlCancelledAppointments.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCancelledAppointments.setModel(new CancelledAppointmentsTableModel());
        TableColumnModel columnModel = this.tblCancelledAppointments.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(40);
        columnModel.getColumn(3).setPreferredWidth(40);
        columnModel.getColumn(4).setPreferredWidth(105);
        columnModel.getColumn(0).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(1).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(2).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(3).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        columnModel.getColumn(4).setHeaderRenderer(new TableHeaderCellBorderRenderer(Color.LIGHT_GRAY));
        
        JTableHeader tableHeader = this.tblCancelledAppointments.getTableHeader();
        tableHeader.setBackground(new Color(220,220,220));
        tableHeader.setOpaque(true);
        jScrollPane2.setViewportView(tblCancelledAppointments);

        javax.swing.GroupLayout pnlCancelledAppointmentsLayout = new javax.swing.GroupLayout(pnlCancelledAppointments);
        pnlCancelledAppointments.setLayout(pnlCancelledAppointmentsLayout);
        pnlCancelledAppointmentsLayout.setHorizontalGroup(
            pnlCancelledAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        pnlCancelledAppointmentsLayout.setVerticalGroup(
            pnlCancelledAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20)    
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    
                    .addComponent(pnlCancelledAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            
            .addGroup(layout.createSequentialGroup()
                .addGap(20)
                .addComponent(pnlCancelledAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold> 

    private void populateCancelledAppointmentsTable(){
        if (tblCancelledAppointments.getModel() == null)
            tblCancelledAppointments.setModel(new CancelledAppointmentsTableModel());
        CancelledAppointmentsTableModel model = 
                (CancelledAppointmentsTableModel)tblCancelledAppointments.getModel();
        model.removeAllElements();
        Iterator<Appointment> it = 
                getMyController().getDescriptor().getControllerDescription().getAppointmentCancellations().iterator();
        while (it.hasNext()){
            model.addElement(it.next());
        }
        this.tblCancelledAppointments.setDefaultRenderer(Duration.class, new AppointmentsTableDurationRenderer());
        
       
        this.tblCancelledAppointments.setDefaultRenderer(LocalDateTime.class, new AppointmentsTableLocalDateRenderer());
        this.tblCancelledAppointments.setDefaultRenderer(Patient.class, new CancelledAppointmentsTablePatientRenderer());
        this.tblCancelledAppointments.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tblCancelledAppointments.getColumnModel();
 
    }
    
    private void btnUncancelSelectedAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUncancelSelectedAppointmentActionPerformed
        int row = this.tblCancelledAppointments.getSelectedRow();
        if (row != -1){
            getMyController().getDescriptor().getViewDescription().setAppointment(((CancelledAppointmentsTableModel)tblCancelledAppointments.
                            getModel()).getElementAt(row)); 
            ActionEvent actionEvent = new ActionEvent(this, 
                    ActionEvent.ACTION_PERFORMED,
                    ViewController.ScheduleViewControllerActionEvent.APPOINTMENT_UNCANCEL_REQUEST.toString());
            this.getMyController().actionPerformed(actionEvent);
            
            /**
             * 13/02/2024 16:01 updated code logic to activate schedule view for selected appt
             */
            //int row = this.tblCancelledAppointments.getSelectedRow();
            LocalDate day = (LocalDate)this.tblCancelledAppointments.getValueAt(row,0);
            getMyController().getDescriptor().getViewDescription().setScheduleDay(day);
            actionEvent = new ActionEvent(
                    this,ActionEvent.ACTION_PERFORMED,
                    ViewController.ScheduleViewControllerActionEvent.SCHEDULE_LIST_VIEW_CONTROLLER_REQUEST.toString());
            this.getMyController().actionPerformed(actionEvent);
            
        }else
            JOptionPane.showMessageDialog(this, "An appointment to uncancel has not been selected");
    }//GEN-LAST:event_btnUncancelSelectedAppointmentActionPerformed

    private void btnGoToScheduleForSelectedAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToScheduleForSelectedAppointmentActionPerformed
        if (this.tblCancelledAppointments.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "An appointment has not been selected");
        }
        else{
            int row = this.tblCancelledAppointments.getSelectedRow();
            LocalDate day = (LocalDate)this.tblCancelledAppointments.getValueAt(row,0);
            getMyController().getDescriptor().getViewDescription().setScheduleDay(day);
            ActionEvent actionEvent = new ActionEvent(
                    this,ActionEvent.ACTION_PERFORMED,
                    ViewController.ScheduleViewControllerActionEvent.SCHEDULE_LIST_VIEW_CONTROLLER_REQUEST.toString());
            this.getMyController().actionPerformed(actionEvent);
        }
    }//GEN-LAST:event_btnGoToScheduleForSelectedAppointmentActionPerformed

    private void btnCloseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseViewActionPerformed
        try{
            setClosed(true);
        }catch (PropertyVetoException ex){
            
        }
    }//GEN-LAST:event_btnCloseViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseView;
    private javax.swing.JButton btnGoToScheduleForSelectedAppointment;
    private javax.swing.JButton btnUncancelSelectedAppointment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCancelledAppointments;
    private javax.swing.JPanel pnlOperations;
    private javax.swing.JTable tblCancelledAppointments;
    // End of variables declaration//GEN-END:variables
}
