/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package theclinic.view.views.modal_views;

import theclinic.controller.PatientViewController;
import theclinic.controller.SystemDefinition;
import theclinic.controller.ViewController;
import theclinic.view.View;
import theclinic.view.views.non_modal_views.DesktopView;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.*;
import java.beans.PropertyVetoException;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/**
 *
 * @author colin
 */
public class ModalDateDialog extends ModalView
                             implements ActionListener{

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalDateDialog(
            View.Viewer myViewType,
            ViewController myController, 
            DesktopView desktopView){
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);  
    }
    
    public enum Actions{
        DATE_DIALOG_CANCEL_REQUEST,
        DATE_DIALOG_OK_REQUEST
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        switch(Actions.valueOf(e.getActionCommand())){
            case DATE_DIALOG_CANCEL_REQUEST ->{
                /**
                 * LocalDateTime = 0001-01-01 01:01 signals the dialog has been cancelled
                 */
                getMyController().getDescriptor().getViewDescription().
                            setProperty(SystemDefinition.Properties.DATE_TIME, LocalDateTime.of(1,1,1,1,1));
                try{
                    setClosed(true);
                }
                catch (PropertyVetoException ex){
                    
                }
                break;
            }
            case DATE_DIALOG_OK_REQUEST ->{
                if (datePicker.getDate()!=null){
                    LocalDateTime dateTime = LocalDateTime.of(datePicker.getDate(),LocalTime.now());
                    getMyController().getDescriptor().getViewDescription().
                            setProperty(SystemDefinition.Properties.DATE_TIME, dateTime);
                    System.out.println("dateTime = " + getMyController().getDescriptor().getViewDescription().getProperty(SystemDefinition.Properties.DATE_TIME));
                }     
                //doActionEventFor(Actions.DATE_DIALOG_OK_REQUEST);
                
                try{
                    setClosed(true);
                }catch (PropertyVetoException ex){
                    
                }
                break;
            }
        }
    }
    
    @Override
    public void initialiseView(){
        initComponents();
        setVisible(true);
        setTitle((String)getMyController().getDescriptor().getControllerDescription().
                getProperty(SystemDefinition.Properties.CAPTION));
        this.btnCancel.setActionCommand(Actions.DATE_DIALOG_CANCEL_REQUEST.toString());
        this.btnOK.setActionCommand(Actions.DATE_DIALOG_OK_REQUEST.toString());
        btnCancel.addActionListener(this);
        btnOK.addActionListener(this);
        
    }

    private void doActionEventFor(Actions action){
        ActionEvent actionEvent = new ActionEvent(
            this,ActionEvent.ACTION_PERFORMED,
            action.toString());
        this.getMyController().actionPerformed(actionEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSelectDate = new javax.swing.JPanel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        pnkActions = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        pnlSelectDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Select date"));

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/datepickerbutton1.png"));
        javax.swing.JButton datePickerButton = datePicker.getComponentToggleCalendarButton();
        datePickerButton.setText("");
        datePickerButton.setIcon(icon);
        DatePickerSettings settings = new DatePickerSettings();
        settings.setFormatForDatesCommonEra(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        settings.setAllowKeyboardEditing(false);
        datePicker.setSettings(settings);

        javax.swing.GroupLayout pnlSelectDateLayout = new javax.swing.GroupLayout(pnlSelectDate);
        pnlSelectDate.setLayout(pnlSelectDateLayout);
        pnlSelectDateLayout.setHorizontalGroup(
            pnlSelectDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectDateLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlSelectDateLayout.setVerticalGroup(
            pnlSelectDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectDateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnkActions.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        btnOK.setText("OK");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout pnkActionsLayout = new javax.swing.GroupLayout(pnkActions);
        pnkActions.setLayout(pnkActionsLayout);
        pnkActionsLayout.setHorizontalGroup(
            pnkActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkActionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnkActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnkActionsLayout.setVerticalGroup(
            pnkActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkActionsLayout.createSequentialGroup()
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlSelectDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(pnkActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnkActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSelectDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JPanel pnkActions;
    private javax.swing.JPanel pnlSelectDate;
    // End of variables declaration//GEN-END:variables
}
