/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package theclinic.view.views.modal_views;

import theclinic.controller.SystemDefinition;
import theclinic.controller.ViewController;
import theclinic.model.entity.Patient;
import theclinic.view.View;
import theclinic.view.views.non_modal_views.DesktopView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
/**
 *
 * @author colin
 */
public class ModalDocumentSenderView extends ModalView
                                implements ActionListener{ //View implements an empty overridden propertyChange method
    
    enum Actions{
        REQUEST_CLOSE_VIEW,
        REQUEST_NEXT_PATIENT_DOCUMENT_PREVIEW,
        REQUEST_PREVIOUS_PATIENT_DOCUMENT_PREVIEW,
        REQUEST_SEND_PATIENT_DOCUMENT,
        REQUEST_TYPE_EMAIL,
        REQUEST_TYPE_LETTER,
        REQUEST_TYPE_SMS
        
    }
    
    public enum State{
        ACTIVE,             //recall date is defined for today or later
        INACTIVE,           //recall date is undefined, or is oprior to today
        SUSPENDED           //a FUTURE appointment exists for the patient
    }

    /**
     * 
     * @param myViewType
     * @param myController
     * @param desktopView 
     */
    public ModalDocumentSenderView(View.Viewer myViewType, 
            ViewController myController,
            DesktopView desktopView) {//ViewMode arg
        setMyController(myController);
        setMyViewType(myViewType);
        setDesktopView(desktopView);  
    } 
    
    @Override
    public void actionPerformed(ActionEvent e){
        
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent e){
        
    }
    
    @Override
    public void initialiseView(){
        this.rdbEmail.setActionCommand(Actions.REQUEST_TYPE_EMAIL.toString());
        this.rdbEmail.addActionListener(this);
        this.rdbLetter.setActionCommand(Actions.REQUEST_TYPE_LETTER.toString());
        this.rdbLetter.addActionListener(this);
        this.rdbSMS.setActionCommand(Actions.REQUEST_TYPE_SMS.toString());
        this.rdbSMS.addActionListener(this);
        this.btnCloseView.setActionCommand(Actions.REQUEST_CLOSE_VIEW.toString());
        this.btnCloseView.addActionListener(this);
        this.btnRequestPreviewForPreviousPatient.addActionListener(this);
        this.btnRequestPreviewForNextPatient.setActionCommand(Actions.REQUEST_NEXT_PATIENT_DOCUMENT_PREVIEW.toString());
        this.btnRequestPreviewForNextPatient.addActionListener(this);
        this.btnRequestPreviewForPreviousPatient.setActionCommand(Actions.REQUEST_PREVIOUS_PATIENT_DOCUMENT_PREVIEW.toString());
        this.btnRequestPreviewForPreviousPatient.addActionListener(this);
        setPatient((Patient)getMyController().getDescriptor().getControllerDescription().
                getProperty(SystemDefinition.Properties.PATIENT));
        setSendType((String)getMyController().getDescriptor().getControllerDescription().
                getProperty(SystemDefinition.Properties.VIEW_MODE).toString());
    }

    private Patient patient = null;
    private void setPatient(Patient value){
        patient = value;
    }
    private Patient getPatient(){
        return patient;
    }
    
    private String sendType = null;
    private void setSendType(String value){
        sendType = value;
        switch(sendType){
            case "EMAIL" ->
                this.rdbEmail.setSelected(true);
            case "LETTER" ->
                this.rdbLetter.setSelected(true);
            case "SMS" ->
                this.rdbSMS.setSelected(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlPatientListForRecall = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rdbEmail = new javax.swing.JRadioButton();
        rdbLetter = new javax.swing.JRadioButton();
        rdbSMS = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        epPreview = new javax.swing.JEditorPane();
        pnlActions = new javax.swing.JPanel();
        btnRequestPreviewForNextPatient = new javax.swing.JButton();
        btnRequestPreviewForPreviousPatient = new javax.swing.JButton();
        btnSendPrintRecall = new javax.swing.JButton();
        btnCloseView = new javax.swing.JButton();

        setTitle("Document to be sent to:- ");

        pnlPatientListForRecall.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview format"));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        rdbEmail.setText("email");

        rdbLetter.setText("letter");

        rdbSMS.setText("sms (phone)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(rdbEmail)
                .addGap(60, 60, 60)
                .addComponent(rdbLetter)
                .addGap(40, 40, 40)
                .addComponent(rdbSMS)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbEmail)
                    .addComponent(rdbLetter)
                    .addComponent(rdbSMS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(epPreview);

        javax.swing.GroupLayout pnlPatientListForRecallLayout = new javax.swing.GroupLayout(pnlPatientListForRecall);
        pnlPatientListForRecall.setLayout(pnlPatientListForRecallLayout);
        pnlPatientListForRecallLayout.setHorizontalGroup(
            pnlPatientListForRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientListForRecallLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlPatientListForRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnlPatientListForRecallLayout.setVerticalGroup(
            pnlPatientListForRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientListForRecallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pnlActions.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        btnRequestPreviewForNextPatient.setText("<html><center>Preview document </center><center>for next</center><center>patient</center></html>");

        btnRequestPreviewForPreviousPatient.setText("<html><center>Preview document</center><center>for previous</center><center>patient</center></html>");

        btnSendPrintRecall.setText("<html><center>Send document</center><center>to patient</center></html>");

        btnCloseView.setText("<html><center>Close</center><center>View</center></html>");

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRequestPreviewForPreviousPatient)
                    .addComponent(btnRequestPreviewForNextPatient)
                    .addComponent(btnSendPrintRecall)
                    .addComponent(btnCloseView))
                .addGap(12, 12, 12))
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnRequestPreviewForNextPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnRequestPreviewForPreviousPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSendPrintRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnCloseView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPatientListForRecall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPatientListForRecall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseView;
    private javax.swing.JButton btnRequestPreviewForNextPatient;
    private javax.swing.JButton btnRequestPreviewForPreviousPatient;
    private javax.swing.JButton btnSendPrintRecall;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane epPreview;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlPatientListForRecall;
    private javax.swing.JRadioButton rdbEmail;
    private javax.swing.JRadioButton rdbLetter;
    private javax.swing.JRadioButton rdbSMS;
    // End of variables declaration//GEN-END:variables
}
